tor: upgrade to tor 0.4.2.6

diff --git a/release/src/router/tor/contrib/client-tools/torify b/release/src/router/tor/contrib/client-tools/torify
--- a/release/src/router/tor/contrib/client-tools/torify
+++ b/release/src/router/tor/contrib/client-tools/torify
@@ -53,7 +53,7 @@ pathfind() {
 
 if pathfind torsocks; then
     exec torsocks "$@"
-    echo "$0: Failed to exec torsocks $@" >&2
+    echo "$0: Failed to exec torsocks $*" >&2
     exit 1
 else
     echo "$0: torsocks not found in your PATH.  Perhaps it isn't installed?  (tsocks is no longer supported, for security reasons.)" >&2
