e2fsprogs: updated to 1.45.6

diff --git a/release/src/router/e2fsprogs/lib/et/compile_et.sh.in b/release/src/router/e2fsprogs/lib/et/compile_et.sh.in
--- a/release/src/router/e2fsprogs/lib/et/compile_et.sh.in
+++ b/release/src/router/e2fsprogs/lib/et/compile_et.sh.in
@@ -2,10 +2,8 @@
 #
 #
 
-datarootdir=@datarootdir@
 AWK=@AWK@
-DIR="${DIR-@datadir@/et}"
-ET_DIR="${ET_DIR-@ET_DIR@}"
+DIR=@datadir@/et
 
 if test "$1" = "--build-tree" ; then
     shift;
@@ -29,13 +27,13 @@ do
   fi
 done
 
+if test -n "$_ET_DIR_OVERRIDE" ; then
+    DIR="$_ET_DIR_OVERRIDE";
+fi
+
 if test ! -f "$DIR/et_h.awk" || test ! -f "$DIR/et_c.awk" ; then
-    DIR="$ET_DIR"
-#    echo "Falling back to $DIR..."
-    if test ! -f "$DIR/et_h.awk" || test ! -f "$DIR/et_c.awk" ; then
-	echo "compile_et: Couldn't find compile_et's template files."
-	exit 1
-    fi
+    echo "compile_et: Couldn't find compile_et's template files."
+    exit 1
 fi
 
 ROOT=`echo $1 | sed -e s/.et$//`
diff --git a/release/src/router/e2fsprogs/tests/f_badcluster/script b/release/src/router/e2fsprogs/tests/f_badcluster/script
--- a/release/src/router/e2fsprogs/tests/f_badcluster/script
+++ b/release/src/router/e2fsprogs/tests/f_badcluster/script
@@ -1,27 +1,29 @@
-if test -x $DEBUGFS_EXE; then
-	IMAGE=$test_dir/../f_badcluster/image.gz
-	OUT=$test_name.log
-	EXP=$test_dir/expect
-	gzip -d < $IMAGE > $TMPFILE
-	$FSCK -fy $TMPFILE 2>&1 | sed -f $cmd_dir/filter.sed > $OUT
-	$FSCK -fy $TMPFILE 2>&1 | sed -f $cmd_dir/filter.sed >> $OUT
-	$FSCK -fy $TMPFILE 2>&1 | sed -f $cmd_dir/filter.sed >> $OUT
-	for i in a b c d e f g; do echo "stat /$i"; done > $TMPFILE.tmp
-	echo "quit" >> $TMPFILE.tmp
-	$DEBUGFS_EXE -f $TMPFILE.tmp $TMPFILE >> $OUT
-	rm -f $TMPFILE.tmp
+if ! test -x $DEBUGFS_EXE; then
+	echo "$test_name: $test_description: skipped (no debugfs)"
+	return 0
+fi
 
-	cmp -s $OUT $EXP
-	status=$?
+IMAGE=$test_dir/../f_badcluster/image.gz
+OUT=$test_name.log
+EXP=$test_dir/expect
+gzip -d < $IMAGE > $TMPFILE
+$FSCK -fy $TMPFILE > $OUT.new 2>&1
+$FSCK -fy $TMPFILE >> $OUT.new 2>&1
+$FSCK -fy $TMPFILE >> $OUT.new 2>&1
+for i in a b c d e f g; do echo "stat /$i"; done > $TMPFILE.cmd
+echo "quit" >> $TMPFILE.cmd
+$DEBUGFS -f $TMPFILE.cmd $TMPFILE >> $OUT.new 2>&1
+sed -f $cmd_dir/filter.sed $OUT.new > $OUT
+rm -f $TMPFILE $TMPFILE.cmd $OUT.new
 
-	if [ "$status" = 0 ]; then
-		echo "$test_name: $test_description: ok"
-		touch $test_name.ok
-	else
-		echo "$test_name: $test_description: failed"
-		diff $DIFF_OPTS $EXP $OUT > $test_name.failed
-		rm -f $test_name.tmp
-	fi
+cmp -s $OUT $EXP
+status=$?
+
+if [ "$status" = 0 ]; then
+	echo "$test_name: $test_description: ok"
+	touch $test_name.ok
 else
-	echo "$test_name: skipped"
+	echo "$test_name: $test_description: failed"
+	diff $DIFF_OPTS $EXP $OUT > $test_name.failed
+	rm -f $test_name.tmp
 fi
diff --git a/release/src/router/e2fsprogs/tests/f_mmp/script b/release/src/router/e2fsprogs/tests/f_mmp/script
--- a/release/src/router/e2fsprogs/tests/f_mmp/script
+++ b/release/src/router/e2fsprogs/tests/f_mmp/script
@@ -1,16 +1,5 @@
 FSCK_OPT=-yf
 
-# use current directory instead of /tmp becase tmpfs doesn't support DIO
-rm -f $TMPFILE
-TMPFILE=$(mktemp ./tmp-$test_name.XXXXXX)
-
-stat -f $TMPFILE | grep -q "Type: tmpfs"
-if [ $? = 0 ]; then
-	rm -f $TMPFILE
-	echo "$test_name: $test_description: skipped for tmpfs (no O_DIRECT)"
-	return 0
-fi
-
 echo "make the test image ..." > $test_name.log
 $MKE2FS -q -F -o Linux -b 4096 -O mmp -E mmp_update_interval=1 $TMPFILE 100 >> $test_name.log 2>&1
 status=$?
@@ -43,6 +32,13 @@ rm -f $MARKFILE
 echo "kill debugfs abruptly (simulates e2fsck failure) ..." >> $test_name.log
 kill_debugfs
 
+$E2MMPSTATUS $TMPFILE > $test_name.log 2>&1
+status=$?
+if [ "$status" != 1 ] ; then
+	echo "$E2MMPSTATUS with EXT2_MMP_SEQ_FSCK passed!" > $test_name.failed
+	echo "$test_name: $test_description: failed"
+	return 1
+fi
 
 echo "e2fsck (should fail mmp_seq = EXT2_MMP_SEQ_FSCK) ..." >> $test_name.log
 $FSCK $FSCK_OPT $TMPFILE >> $test_name.log 2>&1
