build: updated build-all script
Cleanups, added new models, and added option to build a separate image
with the ROG UI for ROG models.

diff --git a/tools/build-all b/tools/build-all
--- a/tools/build-all
+++ b/tools/build-all
@@ -24,6 +24,9 @@ RSYNC_TREE=y
 # Combined RT-AC68U image?
 COMBINED=y
 
+# Build ROG UI image for GT models in addition to regular image
+BUILD_ROGUI=n
+
 ### Uncomment the models you wish to build.
 
 BAC68=y
@@ -50,32 +53,34 @@ BGTAX6000=y
 BXT12=y
 BGTAXE16000=y
 BGTAX11000_PRO=y
+BAX86_PRO=y
 
 ### Branches for each model
-BRANCH_AC68=master
+BRANCH_AC68=386.7_x
 
-BRANCH_AC88=master
-BRANCH_AC3100=master
-BRANCH_AC5300=master
+BRANCH_AC88=386.7_x
+BRANCH_AC3100=386.7_x
+BRANCH_AC5300=49335
 
-BRANCH_AC86=master
-BRANCH_GTAC2900=master
+BRANCH_AC86=386.7_x
+BRANCH_GTAC2900=386.7_x
 
-BRANCH_AX88=master
-BRANCH_GTAX11000=master
+BRANCH_AX88=388_20566
+BRANCH_GTAX11000=388_20566
 
 BRANCH_AX58=master
 BRANCH_AX56=master
 
-BRANCH_AX86=master
-BRANCH_AX68=master
+BRANCH_AX86=386.7_x
+BRANCH_AX68=386.7_x
 BRANCH_GTAXE11000=master
-BRANCH_AC68V4=master
+BRANCH_AC68V4=386.7_x
 
 BRANCH_GTAX6000=master
 BRANCH_XT12=master
 BRANCH_GTAXE16000=master
 BRANCH_GTAX11000_PRO=master
+BRANCH_AX86_PRO=master
 
 ### Paths
 # Store built images there
@@ -101,22 +106,23 @@ build_fw()
 	echo "*** $(date +%R) - Starting building $FWMODEL..."
 	cd "$HOME/$FWPATH" || exit 1
 	if make "$FWMODEL" > "output.txt" 2>&1; then
-		cd image || exit 1
+		cd image || exit
 		if [ "$FWMODEL" = "rt-ac86u" ] || [ "$FWMODEL" = "gt-ac2900" ] || [ "$FWMODEL" = "rt-ax88u" ] || [ "$FWMODEL" = "gt-ax11000" ] ; then
-#			FWNAME="$(find -- *_cferom_ubi.w | head -n 1)"
 			FWNAME="$(find -- *_ubi.w | head -n 1)"
-			ZIPNAME="$(echo "$FWNAME" | sed 's~_cferom_ubi.w~~g').zip"
+			ZIPNAME="$(echo "$FWNAME" | sed 's~_ubi.w~~g').zip"
 		elif [ "$FWMODEL" = "rt-ax58u" ] || [ "$FWMODEL" = "rt-ac68u_v4" ]; then
-                        FWNAME="$(find -- *_cferom_puresqubi.w | head -n 1)"
-                        ZIPNAME="$(echo "$FWNAME" | sed 's~_cferom_puresqubi.w~~g').zip"
+			rm *_cferom_puresqubi.w
+			FWNAME="$(find -- *_puresqubi.w | head -n 1)"
+			ZIPNAME="$(echo "$FWNAME" | sed 's~_puresqubi.w~~g').zip"
 		elif [ "$FWMODEL" = "rt-ax86u" ] || [ "$FWMODEL" = "rt-ax68u" ] ; then
 #			rm *_cferom_pureubi.w	# Broken cferom, do not use until fixed upstream
 			FWNAME="$(find -- *_pureubi.w | head -n 1)"
 			ZIPNAME="$(echo "$FWNAME" | sed 's~_pureubi.w~~g').zip"
-                elif [ "$FWMODEL" = "rt-ax56u" ] || [ "$FWMODEL" = "gt-axe11000" ] ; then
-                        FWNAME="$(find -- *_cferom_pureubi.w | head -n 1)"
-                        ZIPNAME="$(echo "$FWNAME" | sed 's~_cferom_pureubi.w~~g').zip"
-		elif [ "$FWMODEL" = "gt-ax6000" ] || [ "$FWMODEL" = "xt12" ] || [ "$FWMODEL" = "gt-axe16000" ] || [ "$FWMODEL" = "gt-ax11000_pro" ] ; then
+		elif [ "$FWMODEL" = "rt-ax56u" ] || [ "$FWMODEL" = "gt-axe11000" ] ; then
+			rm *_cferom_pureubi.w
+			FWNAME="$(find -- *_pureubi.w | head -n 1)"
+			ZIPNAME="$(echo "$FWNAME" | sed 's~_pureubi.w~~g').zip"
+		elif [ "$FWMODEL" = "gt-ax6000" ] || [ "$FWMODEL" = "xt12" ] || [ "$FWMODEL" = "gt-axe16000" ] || [ "$FWMODEL" = "gt-ax11000_pro" ] || [ "$FWMODEL" = "rt-ax86u_pro" ] ; then
 			FWNAME="$(find -- *_nand_squashfs.pkgtb | head -n 1)"
 			ZIPNAME="$(echo "$FWNAME" | sed 's~_nand_squashfs.pkgtb~~g').zip"
 		else
@@ -124,10 +130,37 @@ build_fw()
 			ZIPNAME="$(echo "$FWNAME" | sed 's~.trx~~g').zip"
 		fi
 		cp "$FWNAME" "$STAGE_LOC/"
-
 		sha256sum "$FWNAME" > sha256sum.sha256
 		zip -qj "$STAGE_LOC/$ZIPNAME" "$FWNAME" "$STAGE_LOC/README-merlin.txt" "$STAGE_LOC"/Changelog*.txt "sha256sum.sha256" 2>/dev/null
 		echo "*** $(date +%R) - Done building $FWMODEL!"
+
+		if [ "$BUILD_ROGUI" = "y" ] && ([ "$FWMODEL" = "gt-axe16000" ] || [ "$FWMODEL" = "gt-ax6000" ] || [ "$FWMODEL" = "gt-ax11000_pro" ] || [ "$FWMODEL" = "gt-ac2900" ] || [ "$FWMODEL" = "gt-ax11000" ] || [ "$FWMODEL" = "gt-axe11000" ]) ; then
+			echo "--- $(date +%R) - Building ROG UI for $FWMODEL"
+			cd ..
+			sed -i 's/ROG_UI=n/ROG_UI=y/' target.mak
+			rm -rf image/*.pkgtb image/*.w .config
+			if make "$FWMODEL" > "output.txt" 2>&1; then
+				cd image
+				if [ "$FWMODEL" = "gt-ax6000" ] || [ "$FWMODEL" = "gt-axe16000" ] || [ "$FWMODEL" = "gt-ax11000_pro" ] ; then
+					FWNAME="$(find -- *rog*_nand_squashfs.pkgtb | head -n 1)"
+				elif [ "$FWMODEL" = "gt-ac2900" ] || [ "$FWMODEL" = "gt-ax11000" ] ; then
+					FWNAME="$(find -- *rog*_ubi.w | head -n 1)"
+				elif [ "$FWMODEL" = "gt-axe11000" ] ; then
+					rm *_cferom_pureubi.w
+					FWNAME="$(find -- *rog*_pureubi.w | head -n 1)"
+				else
+					echo "!!! $(date +%R) - $FWMODEL ROG build failed!"
+					return
+				fi
+				cp "$FWNAME" "$STAGE_LOC/"
+				sha256sum "$FWNAME" >> sha256sum.sha256
+				zip -qj "$STAGE_LOC/$ZIPNAME" "$FWNAME" "sha256sum.sha256" 2>/dev/null
+				echo "*** $(date +%R) - Done building ROG UI for $FWMODEL!"
+			else
+				echo "!!! $(date +%R) - $FWMODEL ROG build failed!"
+				return
+			fi
+		fi
 	else
 		echo "!!! $(date +%R) - $FWMODEL build failed!"
 	fi
@@ -205,13 +238,13 @@ if [ "$BAX86" = "y" ]; then
 	clean_tree amng.ax86 release/src-rt-5.02L.07p2axhnd rt-ax86u $BRANCH_AX86
 fi
 if [ "$BAX68" = "y" ]; then
-        clean_tree amng.ax68 release/src-rt-5.02L.07p2axhnd rt-ax68u $BRANCH_AX68
+	clean_tree amng.ax68 release/src-rt-5.02L.07p2axhnd rt-ax68u $BRANCH_AX68
 fi
 if [ "$BGTAXE11000" = "y" ]; then
 	clean_tree amng.gtaxe11000 release/src-rt-5.02L.07p2axhnd gt-axe11000 $BRANCH_GTAXE11000
 fi
 if [ "$BAC68V4" = "y" ]; then
-        clean_tree amng.ac68v4 release/src-rt-5.02L.07p2axhnd rt-ac68u_v4 $BRANCH_AC68V4
+	clean_tree amng.ac68v4 release/src-rt-5.02L.07p2axhnd rt-ac68u_v4 $BRANCH_AC68V4
 fi
 if [ "$BGTAX6000" = "y" ]; then
 	clean_tree amng.gtax6000 release/src-rt-5.04axhnd.675x gt-ax6000 $BRANCH_GTAX6000
@@ -220,10 +253,13 @@ if [ "$BXT12" = "y" ]; then
 	clean_tree amng.xt12 release/src-rt-5.04axhnd.675x xt12 $BRANCH_XT12
 fi
 if [ "$BGTAXE16000" = "y" ]; then
-        clean_tree amng.gtaxe16000 release/src-rt-5.04axhnd.675x gt-axe16000 $BRANCH_XT12
+	clean_tree amng.gtaxe16000 release/src-rt-5.04axhnd.675x gt-axe16000 $BRANCH_GTAXE16000
 fi
 if [ "$BGTAX11000_PRO" = "y" ]; then
-        clean_tree amng.gtax11000_pro release/src-rt-5.04axhnd.675x gt-ax11000_pro $BRANCH_XT12
+	clean_tree amng.gtax11000pro release/src-rt-5.04axhnd.675x gt-ax11000_pro $BRANCH_GTAX11000_PRO
+fi
+if [ "$BAX86_PRO" = "y" ]; then
+	clean_tree amng.ax86pro release/src-rt-5.04axhnd.675x rt-ax86u_pro $BRANCH_AX86_PRO
 fi
 
 echo "--- $(date +%R) - All trees ready!"
@@ -232,18 +268,23 @@ echo "--- $(date +%R) - All trees ready!"
 
 echo "--- $(date +%R) - Launching all builds"
 if [ "$BGTAX6000" = "y" ]; then
-        build_fw amng.gtax6000/release/src-rt-5.04axhnd.675x gt-ax6000 &
+	build_fw amng.gtax6000/release/src-rt-5.04axhnd.675x gt-ax6000 &
 fi
 
 if [ "$BXT12" = "y" ]; then
-        build_fw amng.xt12/release/src-rt-5.04axhnd.675x xt12 &
+	build_fw amng.xt12/release/src-rt-5.04axhnd.675x xt12 &
 fi
+
+if [ "$BAX86_PRO" = "y" ]; then
+	build_fw amng.ax86pro/release/src-rt-5.04axhnd.675x rt-ax86u_pro &
+fi
+
 if [ "$BGTAX11000_PRO" = "y" ]; then
-        build_fw amng.gtax11000_pro/release/src-rt-5.04axhnd.675x gt-ax11000_pro &
+	build_fw amng.gtax11000pro/release/src-rt-5.04axhnd.675x gt-ax11000_pro &
 fi
 
 if [ "$BGTAXE16000" = "y" ]; then
-        build_fw amng.gtaxe16000/release/src-rt-5.04axhnd.675x gt-axe16000 &
+	build_fw amng.gtaxe16000/release/src-rt-5.04axhnd.675x gt-axe16000 &
 fi
 
 if [ "$BAC86" = "y" ]; then
